# Site settings
title: mikeo.io
email: mikeyaudio@gmail.com
url: https://mikeyaudio.github.io
description: "Working on this thing right now."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: aeb5ce #80B3FF
  secondary: d0d2b3 #FD6E8A
  secondary-dark: 81849f #A2122F

# Footer settings
footer:
  copyright: Mike Ouellette
  location: Dartmouth
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mikeyojojr
  - title: facebook
    url: https://www.facebook.com/mouellettest
  - title: stack-overflow
    url: http://stackoverflow.com/users/3642033/mikeyjojr
  - title: github
    url: https://github.com/mikeyaudio

# Postal address (add as many lines as necessary)
address:
  - line: Dartmouth

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
