# Site settings
name: MikeyAudio
title: Bassman
email: mikeyaudio@gmail.com
description: "This is a test website for UIT curriculum"
baseurl: "/mikeyaudio.github.io"
url: "http://mikeyjojr.com"

# Build settings
markdown: redcarpet
permalinks: pretty
