# Site settings
title: mikeo.io
email: mikeyaudio@gmail.com
url: https://mikeyaudio.github.io
description: "Working on this thing right now."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5c7176 #80B3FF
  secondary: 473c4b #FD6E8A
  secondary-dark: 342b3a #A2122F

# Footer settings
footer:
  copyright: Mike Ouellette
  location: Dartmouth
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mikeyojojr
  - title: stack-overflow
    url: http://stackoverflow.com/users/3642033/mikeyjojr
  - title: github
    url: https://github.com/mikeyaudio
  - title: instagram
    url: https://instagram.com/mikeyojojr/
  - title: linkedin
    url: https://www.linkedin.com/profile/preview?vpa=pub&locale=en_US
    
# Postal address (add as many lines as necessary)
address:
  - line: ''

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
